
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SavedCourse` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SavedCourse
 * 
 */
export type SavedCourseModel = runtime.Types.Result.DefaultSelection<Prisma.$SavedCoursePayload>

export type AggregateSavedCourse = {
  _count: SavedCourseCountAggregateOutputType | null
  _min: SavedCourseMinAggregateOutputType | null
  _max: SavedCourseMaxAggregateOutputType | null
}

export type SavedCourseMinAggregateOutputType = {
  id: string | null
  userId: string | null
  courseId: string | null
  savedAt: Date | null
}

export type SavedCourseMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  courseId: string | null
  savedAt: Date | null
}

export type SavedCourseCountAggregateOutputType = {
  id: number
  userId: number
  courseId: number
  savedAt: number
  _all: number
}


export type SavedCourseMinAggregateInputType = {
  id?: true
  userId?: true
  courseId?: true
  savedAt?: true
}

export type SavedCourseMaxAggregateInputType = {
  id?: true
  userId?: true
  courseId?: true
  savedAt?: true
}

export type SavedCourseCountAggregateInputType = {
  id?: true
  userId?: true
  courseId?: true
  savedAt?: true
  _all?: true
}

export type SavedCourseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SavedCourse to aggregate.
   */
  where?: Prisma.SavedCourseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SavedCourses to fetch.
   */
  orderBy?: Prisma.SavedCourseOrderByWithRelationInput | Prisma.SavedCourseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SavedCourseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SavedCourses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SavedCourses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SavedCourses
  **/
  _count?: true | SavedCourseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SavedCourseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SavedCourseMaxAggregateInputType
}

export type GetSavedCourseAggregateType<T extends SavedCourseAggregateArgs> = {
      [P in keyof T & keyof AggregateSavedCourse]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSavedCourse[P]>
    : Prisma.GetScalarType<T[P], AggregateSavedCourse[P]>
}




export type SavedCourseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SavedCourseWhereInput
  orderBy?: Prisma.SavedCourseOrderByWithAggregationInput | Prisma.SavedCourseOrderByWithAggregationInput[]
  by: Prisma.SavedCourseScalarFieldEnum[] | Prisma.SavedCourseScalarFieldEnum
  having?: Prisma.SavedCourseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SavedCourseCountAggregateInputType | true
  _min?: SavedCourseMinAggregateInputType
  _max?: SavedCourseMaxAggregateInputType
}

export type SavedCourseGroupByOutputType = {
  id: string
  userId: string
  courseId: string
  savedAt: Date
  _count: SavedCourseCountAggregateOutputType | null
  _min: SavedCourseMinAggregateOutputType | null
  _max: SavedCourseMaxAggregateOutputType | null
}

type GetSavedCourseGroupByPayload<T extends SavedCourseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SavedCourseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SavedCourseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SavedCourseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SavedCourseGroupByOutputType[P]>
      }
    >
  >



export type SavedCourseWhereInput = {
  AND?: Prisma.SavedCourseWhereInput | Prisma.SavedCourseWhereInput[]
  OR?: Prisma.SavedCourseWhereInput[]
  NOT?: Prisma.SavedCourseWhereInput | Prisma.SavedCourseWhereInput[]
  id?: Prisma.StringFilter<"SavedCourse"> | string
  userId?: Prisma.StringFilter<"SavedCourse"> | string
  courseId?: Prisma.StringFilter<"SavedCourse"> | string
  savedAt?: Prisma.DateTimeFilter<"SavedCourse"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  course?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.CourseWhereInput>
}

export type SavedCourseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  savedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  course?: Prisma.CourseOrderByWithRelationInput
}

export type SavedCourseWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_courseId?: Prisma.SavedCourseUserIdCourseIdCompoundUniqueInput
  AND?: Prisma.SavedCourseWhereInput | Prisma.SavedCourseWhereInput[]
  OR?: Prisma.SavedCourseWhereInput[]
  NOT?: Prisma.SavedCourseWhereInput | Prisma.SavedCourseWhereInput[]
  userId?: Prisma.StringFilter<"SavedCourse"> | string
  courseId?: Prisma.StringFilter<"SavedCourse"> | string
  savedAt?: Prisma.DateTimeFilter<"SavedCourse"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  course?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.CourseWhereInput>
}, "id" | "userId_courseId">

export type SavedCourseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  savedAt?: Prisma.SortOrder
  _count?: Prisma.SavedCourseCountOrderByAggregateInput
  _max?: Prisma.SavedCourseMaxOrderByAggregateInput
  _min?: Prisma.SavedCourseMinOrderByAggregateInput
}

export type SavedCourseScalarWhereWithAggregatesInput = {
  AND?: Prisma.SavedCourseScalarWhereWithAggregatesInput | Prisma.SavedCourseScalarWhereWithAggregatesInput[]
  OR?: Prisma.SavedCourseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SavedCourseScalarWhereWithAggregatesInput | Prisma.SavedCourseScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SavedCourse"> | string
  userId?: Prisma.StringWithAggregatesFilter<"SavedCourse"> | string
  courseId?: Prisma.StringWithAggregatesFilter<"SavedCourse"> | string
  savedAt?: Prisma.DateTimeWithAggregatesFilter<"SavedCourse"> | Date | string
}

export type SavedCourseCreateInput = {
  id?: string
  savedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSavedInput
  course: Prisma.CourseCreateNestedOneWithoutSavedByInput
}

export type SavedCourseUncheckedCreateInput = {
  id?: string
  userId: string
  courseId: string
  savedAt?: Date | string
}

export type SavedCourseUpdateInput = {
  savedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSavedNestedInput
  course?: Prisma.CourseUpdateOneRequiredWithoutSavedByNestedInput
}

export type SavedCourseUncheckedUpdateInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  courseId?: Prisma.StringFieldUpdateOperationsInput | string
  savedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SavedCourseCreateManyInput = {
  id?: string
  userId: string
  courseId: string
  savedAt?: Date | string
}

export type SavedCourseUpdateManyMutationInput = {
  savedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SavedCourseUncheckedUpdateManyInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  courseId?: Prisma.StringFieldUpdateOperationsInput | string
  savedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SavedCourseListRelationFilter = {
  every?: Prisma.SavedCourseWhereInput
  some?: Prisma.SavedCourseWhereInput
  none?: Prisma.SavedCourseWhereInput
}

export type SavedCourseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SavedCourseUserIdCourseIdCompoundUniqueInput = {
  userId: string
  courseId: string
}

export type SavedCourseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  savedAt?: Prisma.SortOrder
}

export type SavedCourseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  savedAt?: Prisma.SortOrder
}

export type SavedCourseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  savedAt?: Prisma.SortOrder
}

export type SavedCourseCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SavedCourseCreateWithoutUserInput, Prisma.SavedCourseUncheckedCreateWithoutUserInput> | Prisma.SavedCourseCreateWithoutUserInput[] | Prisma.SavedCourseUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SavedCourseCreateOrConnectWithoutUserInput | Prisma.SavedCourseCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SavedCourseCreateManyUserInputEnvelope
  connect?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
}

export type SavedCourseUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SavedCourseCreateWithoutUserInput, Prisma.SavedCourseUncheckedCreateWithoutUserInput> | Prisma.SavedCourseCreateWithoutUserInput[] | Prisma.SavedCourseUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SavedCourseCreateOrConnectWithoutUserInput | Prisma.SavedCourseCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SavedCourseCreateManyUserInputEnvelope
  connect?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
}

export type SavedCourseUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SavedCourseCreateWithoutUserInput, Prisma.SavedCourseUncheckedCreateWithoutUserInput> | Prisma.SavedCourseCreateWithoutUserInput[] | Prisma.SavedCourseUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SavedCourseCreateOrConnectWithoutUserInput | Prisma.SavedCourseCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SavedCourseUpsertWithWhereUniqueWithoutUserInput | Prisma.SavedCourseUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SavedCourseCreateManyUserInputEnvelope
  set?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
  disconnect?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
  delete?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
  connect?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
  update?: Prisma.SavedCourseUpdateWithWhereUniqueWithoutUserInput | Prisma.SavedCourseUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SavedCourseUpdateManyWithWhereWithoutUserInput | Prisma.SavedCourseUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SavedCourseScalarWhereInput | Prisma.SavedCourseScalarWhereInput[]
}

export type SavedCourseUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SavedCourseCreateWithoutUserInput, Prisma.SavedCourseUncheckedCreateWithoutUserInput> | Prisma.SavedCourseCreateWithoutUserInput[] | Prisma.SavedCourseUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SavedCourseCreateOrConnectWithoutUserInput | Prisma.SavedCourseCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SavedCourseUpsertWithWhereUniqueWithoutUserInput | Prisma.SavedCourseUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SavedCourseCreateManyUserInputEnvelope
  set?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
  disconnect?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
  delete?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
  connect?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
  update?: Prisma.SavedCourseUpdateWithWhereUniqueWithoutUserInput | Prisma.SavedCourseUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SavedCourseUpdateManyWithWhereWithoutUserInput | Prisma.SavedCourseUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SavedCourseScalarWhereInput | Prisma.SavedCourseScalarWhereInput[]
}

export type SavedCourseCreateNestedManyWithoutCourseInput = {
  create?: Prisma.XOR<Prisma.SavedCourseCreateWithoutCourseInput, Prisma.SavedCourseUncheckedCreateWithoutCourseInput> | Prisma.SavedCourseCreateWithoutCourseInput[] | Prisma.SavedCourseUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.SavedCourseCreateOrConnectWithoutCourseInput | Prisma.SavedCourseCreateOrConnectWithoutCourseInput[]
  createMany?: Prisma.SavedCourseCreateManyCourseInputEnvelope
  connect?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
}

export type SavedCourseUncheckedCreateNestedManyWithoutCourseInput = {
  create?: Prisma.XOR<Prisma.SavedCourseCreateWithoutCourseInput, Prisma.SavedCourseUncheckedCreateWithoutCourseInput> | Prisma.SavedCourseCreateWithoutCourseInput[] | Prisma.SavedCourseUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.SavedCourseCreateOrConnectWithoutCourseInput | Prisma.SavedCourseCreateOrConnectWithoutCourseInput[]
  createMany?: Prisma.SavedCourseCreateManyCourseInputEnvelope
  connect?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
}

export type SavedCourseUpdateManyWithoutCourseNestedInput = {
  create?: Prisma.XOR<Prisma.SavedCourseCreateWithoutCourseInput, Prisma.SavedCourseUncheckedCreateWithoutCourseInput> | Prisma.SavedCourseCreateWithoutCourseInput[] | Prisma.SavedCourseUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.SavedCourseCreateOrConnectWithoutCourseInput | Prisma.SavedCourseCreateOrConnectWithoutCourseInput[]
  upsert?: Prisma.SavedCourseUpsertWithWhereUniqueWithoutCourseInput | Prisma.SavedCourseUpsertWithWhereUniqueWithoutCourseInput[]
  createMany?: Prisma.SavedCourseCreateManyCourseInputEnvelope
  set?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
  disconnect?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
  delete?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
  connect?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
  update?: Prisma.SavedCourseUpdateWithWhereUniqueWithoutCourseInput | Prisma.SavedCourseUpdateWithWhereUniqueWithoutCourseInput[]
  updateMany?: Prisma.SavedCourseUpdateManyWithWhereWithoutCourseInput | Prisma.SavedCourseUpdateManyWithWhereWithoutCourseInput[]
  deleteMany?: Prisma.SavedCourseScalarWhereInput | Prisma.SavedCourseScalarWhereInput[]
}

export type SavedCourseUncheckedUpdateManyWithoutCourseNestedInput = {
  create?: Prisma.XOR<Prisma.SavedCourseCreateWithoutCourseInput, Prisma.SavedCourseUncheckedCreateWithoutCourseInput> | Prisma.SavedCourseCreateWithoutCourseInput[] | Prisma.SavedCourseUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.SavedCourseCreateOrConnectWithoutCourseInput | Prisma.SavedCourseCreateOrConnectWithoutCourseInput[]
  upsert?: Prisma.SavedCourseUpsertWithWhereUniqueWithoutCourseInput | Prisma.SavedCourseUpsertWithWhereUniqueWithoutCourseInput[]
  createMany?: Prisma.SavedCourseCreateManyCourseInputEnvelope
  set?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
  disconnect?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
  delete?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
  connect?: Prisma.SavedCourseWhereUniqueInput | Prisma.SavedCourseWhereUniqueInput[]
  update?: Prisma.SavedCourseUpdateWithWhereUniqueWithoutCourseInput | Prisma.SavedCourseUpdateWithWhereUniqueWithoutCourseInput[]
  updateMany?: Prisma.SavedCourseUpdateManyWithWhereWithoutCourseInput | Prisma.SavedCourseUpdateManyWithWhereWithoutCourseInput[]
  deleteMany?: Prisma.SavedCourseScalarWhereInput | Prisma.SavedCourseScalarWhereInput[]
}

export type SavedCourseCreateWithoutUserInput = {
  id?: string
  savedAt?: Date | string
  course: Prisma.CourseCreateNestedOneWithoutSavedByInput
}

export type SavedCourseUncheckedCreateWithoutUserInput = {
  id?: string
  courseId: string
  savedAt?: Date | string
}

export type SavedCourseCreateOrConnectWithoutUserInput = {
  where: Prisma.SavedCourseWhereUniqueInput
  create: Prisma.XOR<Prisma.SavedCourseCreateWithoutUserInput, Prisma.SavedCourseUncheckedCreateWithoutUserInput>
}

export type SavedCourseCreateManyUserInputEnvelope = {
  data: Prisma.SavedCourseCreateManyUserInput | Prisma.SavedCourseCreateManyUserInput[]
}

export type SavedCourseUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.SavedCourseWhereUniqueInput
  update: Prisma.XOR<Prisma.SavedCourseUpdateWithoutUserInput, Prisma.SavedCourseUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.SavedCourseCreateWithoutUserInput, Prisma.SavedCourseUncheckedCreateWithoutUserInput>
}

export type SavedCourseUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.SavedCourseWhereUniqueInput
  data: Prisma.XOR<Prisma.SavedCourseUpdateWithoutUserInput, Prisma.SavedCourseUncheckedUpdateWithoutUserInput>
}

export type SavedCourseUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.SavedCourseScalarWhereInput
  data: Prisma.XOR<Prisma.SavedCourseUpdateManyMutationInput, Prisma.SavedCourseUncheckedUpdateManyWithoutUserInput>
}

export type SavedCourseScalarWhereInput = {
  AND?: Prisma.SavedCourseScalarWhereInput | Prisma.SavedCourseScalarWhereInput[]
  OR?: Prisma.SavedCourseScalarWhereInput[]
  NOT?: Prisma.SavedCourseScalarWhereInput | Prisma.SavedCourseScalarWhereInput[]
  id?: Prisma.StringFilter<"SavedCourse"> | string
  userId?: Prisma.StringFilter<"SavedCourse"> | string
  courseId?: Prisma.StringFilter<"SavedCourse"> | string
  savedAt?: Prisma.DateTimeFilter<"SavedCourse"> | Date | string
}

export type SavedCourseCreateWithoutCourseInput = {
  id?: string
  savedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSavedInput
}

export type SavedCourseUncheckedCreateWithoutCourseInput = {
  id?: string
  userId: string
  savedAt?: Date | string
}

export type SavedCourseCreateOrConnectWithoutCourseInput = {
  where: Prisma.SavedCourseWhereUniqueInput
  create: Prisma.XOR<Prisma.SavedCourseCreateWithoutCourseInput, Prisma.SavedCourseUncheckedCreateWithoutCourseInput>
}

export type SavedCourseCreateManyCourseInputEnvelope = {
  data: Prisma.SavedCourseCreateManyCourseInput | Prisma.SavedCourseCreateManyCourseInput[]
}

export type SavedCourseUpsertWithWhereUniqueWithoutCourseInput = {
  where: Prisma.SavedCourseWhereUniqueInput
  update: Prisma.XOR<Prisma.SavedCourseUpdateWithoutCourseInput, Prisma.SavedCourseUncheckedUpdateWithoutCourseInput>
  create: Prisma.XOR<Prisma.SavedCourseCreateWithoutCourseInput, Prisma.SavedCourseUncheckedCreateWithoutCourseInput>
}

export type SavedCourseUpdateWithWhereUniqueWithoutCourseInput = {
  where: Prisma.SavedCourseWhereUniqueInput
  data: Prisma.XOR<Prisma.SavedCourseUpdateWithoutCourseInput, Prisma.SavedCourseUncheckedUpdateWithoutCourseInput>
}

export type SavedCourseUpdateManyWithWhereWithoutCourseInput = {
  where: Prisma.SavedCourseScalarWhereInput
  data: Prisma.XOR<Prisma.SavedCourseUpdateManyMutationInput, Prisma.SavedCourseUncheckedUpdateManyWithoutCourseInput>
}

export type SavedCourseCreateManyUserInput = {
  id?: string
  courseId: string
  savedAt?: Date | string
}

export type SavedCourseUpdateWithoutUserInput = {
  savedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  course?: Prisma.CourseUpdateOneRequiredWithoutSavedByNestedInput
}

export type SavedCourseUncheckedUpdateWithoutUserInput = {
  courseId?: Prisma.StringFieldUpdateOperationsInput | string
  savedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SavedCourseUncheckedUpdateManyWithoutUserInput = {
  courseId?: Prisma.StringFieldUpdateOperationsInput | string
  savedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SavedCourseCreateManyCourseInput = {
  id?: string
  userId: string
  savedAt?: Date | string
}

export type SavedCourseUpdateWithoutCourseInput = {
  savedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSavedNestedInput
}

export type SavedCourseUncheckedUpdateWithoutCourseInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  savedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SavedCourseUncheckedUpdateManyWithoutCourseInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  savedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SavedCourseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  courseId?: boolean
  savedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["savedCourse"]>



export type SavedCourseSelectScalar = {
  id?: boolean
  userId?: boolean
  courseId?: boolean
  savedAt?: boolean
}

export type SavedCourseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "courseId" | "savedAt", ExtArgs["result"]["savedCourse"]>
export type SavedCourseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}

export type $SavedCoursePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SavedCourse"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    course: Prisma.$CoursePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    courseId: string
    savedAt: Date
  }, ExtArgs["result"]["savedCourse"]>
  composites: {}
}

export type SavedCourseGetPayload<S extends boolean | null | undefined | SavedCourseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SavedCoursePayload, S>

export type SavedCourseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SavedCourseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SavedCourseCountAggregateInputType | true
  }

export interface SavedCourseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SavedCourse'], meta: { name: 'SavedCourse' } }
  /**
   * Find zero or one SavedCourse that matches the filter.
   * @param {SavedCourseFindUniqueArgs} args - Arguments to find a SavedCourse
   * @example
   * // Get one SavedCourse
   * const savedCourse = await prisma.savedCourse.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SavedCourseFindUniqueArgs>(args: Prisma.SelectSubset<T, SavedCourseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SavedCourseClient<runtime.Types.Result.GetResult<Prisma.$SavedCoursePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SavedCourse that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SavedCourseFindUniqueOrThrowArgs} args - Arguments to find a SavedCourse
   * @example
   * // Get one SavedCourse
   * const savedCourse = await prisma.savedCourse.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SavedCourseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SavedCourseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SavedCourseClient<runtime.Types.Result.GetResult<Prisma.$SavedCoursePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SavedCourse that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedCourseFindFirstArgs} args - Arguments to find a SavedCourse
   * @example
   * // Get one SavedCourse
   * const savedCourse = await prisma.savedCourse.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SavedCourseFindFirstArgs>(args?: Prisma.SelectSubset<T, SavedCourseFindFirstArgs<ExtArgs>>): Prisma.Prisma__SavedCourseClient<runtime.Types.Result.GetResult<Prisma.$SavedCoursePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SavedCourse that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedCourseFindFirstOrThrowArgs} args - Arguments to find a SavedCourse
   * @example
   * // Get one SavedCourse
   * const savedCourse = await prisma.savedCourse.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SavedCourseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SavedCourseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SavedCourseClient<runtime.Types.Result.GetResult<Prisma.$SavedCoursePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SavedCourses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedCourseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SavedCourses
   * const savedCourses = await prisma.savedCourse.findMany()
   * 
   * // Get first 10 SavedCourses
   * const savedCourses = await prisma.savedCourse.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const savedCourseWithIdOnly = await prisma.savedCourse.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SavedCourseFindManyArgs>(args?: Prisma.SelectSubset<T, SavedCourseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SavedCoursePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SavedCourse.
   * @param {SavedCourseCreateArgs} args - Arguments to create a SavedCourse.
   * @example
   * // Create one SavedCourse
   * const SavedCourse = await prisma.savedCourse.create({
   *   data: {
   *     // ... data to create a SavedCourse
   *   }
   * })
   * 
   */
  create<T extends SavedCourseCreateArgs>(args: Prisma.SelectSubset<T, SavedCourseCreateArgs<ExtArgs>>): Prisma.Prisma__SavedCourseClient<runtime.Types.Result.GetResult<Prisma.$SavedCoursePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SavedCourses.
   * @param {SavedCourseCreateManyArgs} args - Arguments to create many SavedCourses.
   * @example
   * // Create many SavedCourses
   * const savedCourse = await prisma.savedCourse.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SavedCourseCreateManyArgs>(args?: Prisma.SelectSubset<T, SavedCourseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a SavedCourse.
   * @param {SavedCourseDeleteArgs} args - Arguments to delete one SavedCourse.
   * @example
   * // Delete one SavedCourse
   * const SavedCourse = await prisma.savedCourse.delete({
   *   where: {
   *     // ... filter to delete one SavedCourse
   *   }
   * })
   * 
   */
  delete<T extends SavedCourseDeleteArgs>(args: Prisma.SelectSubset<T, SavedCourseDeleteArgs<ExtArgs>>): Prisma.Prisma__SavedCourseClient<runtime.Types.Result.GetResult<Prisma.$SavedCoursePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SavedCourse.
   * @param {SavedCourseUpdateArgs} args - Arguments to update one SavedCourse.
   * @example
   * // Update one SavedCourse
   * const savedCourse = await prisma.savedCourse.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SavedCourseUpdateArgs>(args: Prisma.SelectSubset<T, SavedCourseUpdateArgs<ExtArgs>>): Prisma.Prisma__SavedCourseClient<runtime.Types.Result.GetResult<Prisma.$SavedCoursePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SavedCourses.
   * @param {SavedCourseDeleteManyArgs} args - Arguments to filter SavedCourses to delete.
   * @example
   * // Delete a few SavedCourses
   * const { count } = await prisma.savedCourse.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SavedCourseDeleteManyArgs>(args?: Prisma.SelectSubset<T, SavedCourseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SavedCourses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedCourseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SavedCourses
   * const savedCourse = await prisma.savedCourse.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SavedCourseUpdateManyArgs>(args: Prisma.SelectSubset<T, SavedCourseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one SavedCourse.
   * @param {SavedCourseUpsertArgs} args - Arguments to update or create a SavedCourse.
   * @example
   * // Update or create a SavedCourse
   * const savedCourse = await prisma.savedCourse.upsert({
   *   create: {
   *     // ... data to create a SavedCourse
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SavedCourse we want to update
   *   }
   * })
   */
  upsert<T extends SavedCourseUpsertArgs>(args: Prisma.SelectSubset<T, SavedCourseUpsertArgs<ExtArgs>>): Prisma.Prisma__SavedCourseClient<runtime.Types.Result.GetResult<Prisma.$SavedCoursePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SavedCourses that matches the filter.
   * @param {SavedCourseFindRawArgs} args - Select which filters you would like to apply.
   * @example
   * const savedCourse = await prisma.savedCourse.findRaw({
   *   filter: { age: { $gt: 25 } }
   * })
   */
  findRaw(args?: Prisma.SavedCourseFindRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>

  /**
   * Perform aggregation operations on a SavedCourse.
   * @param {SavedCourseAggregateRawArgs} args - Select which aggregations you would like to apply.
   * @example
   * const savedCourse = await prisma.savedCourse.aggregateRaw({
   *   pipeline: [
   *     { $match: { status: "registered" } },
   *     { $group: { _id: "$country", total: { $sum: 1 } } }
   *   ]
   * })
   */
  aggregateRaw(args?: Prisma.SavedCourseAggregateRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>


  /**
   * Count the number of SavedCourses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedCourseCountArgs} args - Arguments to filter SavedCourses to count.
   * @example
   * // Count the number of SavedCourses
   * const count = await prisma.savedCourse.count({
   *   where: {
   *     // ... the filter for the SavedCourses we want to count
   *   }
   * })
  **/
  count<T extends SavedCourseCountArgs>(
    args?: Prisma.Subset<T, SavedCourseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SavedCourseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SavedCourse.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedCourseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SavedCourseAggregateArgs>(args: Prisma.Subset<T, SavedCourseAggregateArgs>): Prisma.PrismaPromise<GetSavedCourseAggregateType<T>>

  /**
   * Group by SavedCourse.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedCourseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SavedCourseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SavedCourseGroupByArgs['orderBy'] }
      : { orderBy?: SavedCourseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SavedCourseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSavedCourseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SavedCourse model
 */
readonly fields: SavedCourseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SavedCourse.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SavedCourseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  course<T extends Prisma.CourseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CourseDefaultArgs<ExtArgs>>): Prisma.Prisma__CourseClient<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SavedCourse model
 */
export interface SavedCourseFieldRefs {
  readonly id: Prisma.FieldRef<"SavedCourse", 'String'>
  readonly userId: Prisma.FieldRef<"SavedCourse", 'String'>
  readonly courseId: Prisma.FieldRef<"SavedCourse", 'String'>
  readonly savedAt: Prisma.FieldRef<"SavedCourse", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SavedCourse findUnique
 */
export type SavedCourseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCourse
   */
  select?: Prisma.SavedCourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCourse
   */
  omit?: Prisma.SavedCourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCourseInclude<ExtArgs> | null
  /**
   * Filter, which SavedCourse to fetch.
   */
  where: Prisma.SavedCourseWhereUniqueInput
}

/**
 * SavedCourse findUniqueOrThrow
 */
export type SavedCourseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCourse
   */
  select?: Prisma.SavedCourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCourse
   */
  omit?: Prisma.SavedCourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCourseInclude<ExtArgs> | null
  /**
   * Filter, which SavedCourse to fetch.
   */
  where: Prisma.SavedCourseWhereUniqueInput
}

/**
 * SavedCourse findFirst
 */
export type SavedCourseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCourse
   */
  select?: Prisma.SavedCourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCourse
   */
  omit?: Prisma.SavedCourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCourseInclude<ExtArgs> | null
  /**
   * Filter, which SavedCourse to fetch.
   */
  where?: Prisma.SavedCourseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SavedCourses to fetch.
   */
  orderBy?: Prisma.SavedCourseOrderByWithRelationInput | Prisma.SavedCourseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SavedCourses.
   */
  cursor?: Prisma.SavedCourseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SavedCourses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SavedCourses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SavedCourses.
   */
  distinct?: Prisma.SavedCourseScalarFieldEnum | Prisma.SavedCourseScalarFieldEnum[]
}

/**
 * SavedCourse findFirstOrThrow
 */
export type SavedCourseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCourse
   */
  select?: Prisma.SavedCourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCourse
   */
  omit?: Prisma.SavedCourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCourseInclude<ExtArgs> | null
  /**
   * Filter, which SavedCourse to fetch.
   */
  where?: Prisma.SavedCourseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SavedCourses to fetch.
   */
  orderBy?: Prisma.SavedCourseOrderByWithRelationInput | Prisma.SavedCourseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SavedCourses.
   */
  cursor?: Prisma.SavedCourseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SavedCourses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SavedCourses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SavedCourses.
   */
  distinct?: Prisma.SavedCourseScalarFieldEnum | Prisma.SavedCourseScalarFieldEnum[]
}

/**
 * SavedCourse findMany
 */
export type SavedCourseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCourse
   */
  select?: Prisma.SavedCourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCourse
   */
  omit?: Prisma.SavedCourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCourseInclude<ExtArgs> | null
  /**
   * Filter, which SavedCourses to fetch.
   */
  where?: Prisma.SavedCourseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SavedCourses to fetch.
   */
  orderBy?: Prisma.SavedCourseOrderByWithRelationInput | Prisma.SavedCourseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SavedCourses.
   */
  cursor?: Prisma.SavedCourseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SavedCourses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SavedCourses.
   */
  skip?: number
  distinct?: Prisma.SavedCourseScalarFieldEnum | Prisma.SavedCourseScalarFieldEnum[]
}

/**
 * SavedCourse create
 */
export type SavedCourseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCourse
   */
  select?: Prisma.SavedCourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCourse
   */
  omit?: Prisma.SavedCourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCourseInclude<ExtArgs> | null
  /**
   * The data needed to create a SavedCourse.
   */
  data: Prisma.XOR<Prisma.SavedCourseCreateInput, Prisma.SavedCourseUncheckedCreateInput>
}

/**
 * SavedCourse createMany
 */
export type SavedCourseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SavedCourses.
   */
  data: Prisma.SavedCourseCreateManyInput | Prisma.SavedCourseCreateManyInput[]
}

/**
 * SavedCourse update
 */
export type SavedCourseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCourse
   */
  select?: Prisma.SavedCourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCourse
   */
  omit?: Prisma.SavedCourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCourseInclude<ExtArgs> | null
  /**
   * The data needed to update a SavedCourse.
   */
  data: Prisma.XOR<Prisma.SavedCourseUpdateInput, Prisma.SavedCourseUncheckedUpdateInput>
  /**
   * Choose, which SavedCourse to update.
   */
  where: Prisma.SavedCourseWhereUniqueInput
}

/**
 * SavedCourse updateMany
 */
export type SavedCourseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SavedCourses.
   */
  data: Prisma.XOR<Prisma.SavedCourseUpdateManyMutationInput, Prisma.SavedCourseUncheckedUpdateManyInput>
  /**
   * Filter which SavedCourses to update
   */
  where?: Prisma.SavedCourseWhereInput
  /**
   * Limit how many SavedCourses to update.
   */
  limit?: number
}

/**
 * SavedCourse upsert
 */
export type SavedCourseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCourse
   */
  select?: Prisma.SavedCourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCourse
   */
  omit?: Prisma.SavedCourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCourseInclude<ExtArgs> | null
  /**
   * The filter to search for the SavedCourse to update in case it exists.
   */
  where: Prisma.SavedCourseWhereUniqueInput
  /**
   * In case the SavedCourse found by the `where` argument doesn't exist, create a new SavedCourse with this data.
   */
  create: Prisma.XOR<Prisma.SavedCourseCreateInput, Prisma.SavedCourseUncheckedCreateInput>
  /**
   * In case the SavedCourse was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SavedCourseUpdateInput, Prisma.SavedCourseUncheckedUpdateInput>
}

/**
 * SavedCourse delete
 */
export type SavedCourseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCourse
   */
  select?: Prisma.SavedCourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCourse
   */
  omit?: Prisma.SavedCourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCourseInclude<ExtArgs> | null
  /**
   * Filter which SavedCourse to delete.
   */
  where: Prisma.SavedCourseWhereUniqueInput
}

/**
 * SavedCourse deleteMany
 */
export type SavedCourseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SavedCourses to delete
   */
  where?: Prisma.SavedCourseWhereInput
  /**
   * Limit how many SavedCourses to delete.
   */
  limit?: number
}

/**
 * SavedCourse findRaw
 */
export type SavedCourseFindRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The query predicate filter. If unspecified, then all documents in the collection will match the predicate. ${@link https://docs.mongodb.com/manual/reference/operator/query MongoDB Docs}.
   */
  filter?: runtime.InputJsonValue
  /**
   * Additional options to pass to the `find` command ${@link https://docs.mongodb.com/manual/reference/command/find/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * SavedCourse aggregateRaw
 */
export type SavedCourseAggregateRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * An array of aggregation stages to process and transform the document stream via the aggregation pipeline. ${@link https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline MongoDB Docs}.
   */
  pipeline?: runtime.InputJsonValue[]
  /**
   * Additional options to pass to the `aggregate` command ${@link https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * SavedCourse without action
 */
export type SavedCourseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCourse
   */
  select?: Prisma.SavedCourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCourse
   */
  omit?: Prisma.SavedCourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCourseInclude<ExtArgs> | null
}
